---
title: "medition_shared_info_bias"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up

```{r}
require(tidyverse)
require('lme4')
require(psych)
require(mediation)
```
# Load and prep data

```{r}
shared_df <- read_csv("data/shared_unshared_inf.csv")[,1:7]
group_df <- read_csv("data/group_level_data.csv")
group_df <- group_df %>%
  separate(condition, c('group_structure','TMS'), sep = '_', remove = FALSE) %>% 
  mutate(binary_decision = decision == "C") 

# Exclude groups
group_df <- group_df %>% 
  filter(!group %in% c(14, 80))
shared_df <- shared_df %>% 
  filter(!group %in% c(14, 80))


# Collapse the two different kind of shared information (fully and partially shared)
shared_df <- shared_df %>%
    mutate(simple_kind = ifelse(kind == 1, 'unshared', 'shared'))

# Create joint dataframe
joined_df <- shared_df %>%
  left_join(group_df[, c("group", "binary_decision", "group_structure", "TMS")], by= 'group')
```
# MEDIATION 

# 1. of the effect of group structure on decision quality

## mentioning bias 

```{r}
shared_mentioning_bias <- joined_df %>%
    group_by(group_structure, group, simple_kind) %>%
    summarise(mentioning_rate = sum(mentioning)/n(), 
              binary_decision = binary_decision[1] * 1) %>% 
  group_by(group_structure, group) %>%
  do(
    data.frame(
      bias = .[.$simple_kind=='shared', 'mentioning_rate'] / (.[.$simple_kind=='unshared', 'mentioning_rate'] + .[.$simple_kind=='shared', 'mentioning_rate']), binary_decision = .[1, 'binary_decision'])) %>% 
  rename(bias = mentioning_rate)

shared_mentioning_bias
```
# mediation test

```{r}
med.model <- lm(bias ~ group_structure, data= shared_mentioning_bias)
full.model <- glm(binary_decision ~ bias + group_structure, data = shared_mentioning_bias, family = 'binomial')
m.out <- mediate(med.model, full.model, treat = "group_structure", mediator = "bias")
summary(m.out)
plot(m.out)

```

## repetition bias

```{r}
shared_repetition_bias <- joined_df %>%
    group_by(group_structure, group, simple_kind) %>%
    summarise(repetition_rate = sum(repetition)/sum(mentioning), 
              binary_decision = binary_decision[1] * 1) %>% 
    group_by(group_structure, group) %>%
    do(
      data.frame(
        bias = .[.$simple_kind=='shared', 'repetition_rate'] / (.[.$simple_kind=='unshared', 'repetition_rate'] + .[.$simple_kind=='shared', 'repetition_rate']), 
        binary_decision = .[1, 'binary_decision']
      )
    ) %>% 
  rename(bias = repetition_rate)


med.model_2 <- lm(bias ~ group_structure, data= shared_repetition_bias)
full.model_2 <- glm(binary_decision ~ bias + group_structure, data = shared_repetition_bias, family = 'binomial')
m.out_2 <- mediate(med.model_2, full.model_2, treat = "group_structure", mediator = "bias")
summary(m.out_2)
plot(m.out)

```

# 2. of the effect of TMS on decision quality

```{r}

```

