---
title: "Data Exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r}
library(tidyverse)
library(lubridate)
library(readr)
library(forcats)
library(stringr)
```
# Data prep

## load

```{r}
survey_data <- read_csv("data/survey_results.csv")
```
## manipulate

```{r}
survey_data <- rownames_to_column(survey_data, var = "participant") 
survey_data <- mutate_at(survey_data, vars(indiv_team_tenure, core_team_tenure), as.factor)
View(survey_data)
```
# Exploring variables

## team size and tenure
```{r}
ggplot(survey_data, aes(team_members)) +
  geom_histogram(binwidth = 10)

survey_data %>% 
  mutate(indiv_team_tenure = indiv_team_tenure %>% 
  fct_infreq) %>% 
  ggplot(aes(indiv_team_tenure)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))

survey_data$indiv_team_tenure <- fct_relevel(survey_data$indiv_team_tenure, "Less than 3 months", "3 _ 6 months", "6 _ 12 months")

summary(survey_data$indiv_team_tenure)

survey_data %>% 
  ggplot(aes(indiv_team_tenure)) + 
  geom_bar() + 
  xlab("indiv_team_tenure") +
  theme(axis.text.x = element_text(angle = 90)) 

summary(survey_data$core_team_tenure)

survey_data %>% 
  ggplot(aes(core_team_tenure)) + 
  geom_bar() + 
  xlab("team tenure in months") +
  theme(axis.text.x = element_text(angle = 90)) 
```
## agile 

```{r}
survey_data %>% 
  count(agile_method) 

survey_data %>% 
  mutate(agile_method = agile_method == "Yes") %>%
  summarise(percent_agile = sum(agile_method, na.rm = T)/n() * 100)

# looking into the character vector on which agile methods were used

str_agile_method <- survey_data$which_agile_method

str_agile_method <- str_to_lower(str_agile_method)

str_agile_method 

scrum <- str_detect(str_agile_method, "scrum")
summary(scrum)

lean <- str_detect(str_agile_method, "lean")
summary(lean)

kanban <- str_detect(str_agile_method, "ban")
summary(kanban)
```
## manager

```{r}
survey_data %>% 
  mutate(manager_type = manager_type == "Internal") %>% 
  summarise(percent_internal_manager = sum(manager_type/n() * 100))
```
## gender

```{r}
survey_data <- survey_data %>% 
  mutate(gender = gender == "Male")

survey_data %>% 
  summarise(percent_male = sum(gender)/n() * 100)
```
## work experience

```{r}
survey_data %>% 
  ggplot(aes(work_experience)) +
  geom_histogram(binwidth = 5)

summary(survey_data$work_experience)

survey_data %>% 
  filter(!work_experience > 40) %>% 
  dplyr::select(work_experience) %>% 
  summarise(mean_work_exp = mean(work_experience))

survey_data %>% 
  filter(work_experience > 45)

# participant 1074 needs to be excluded 
```
## career level

```{r}
survey_data <- mutate_at(survey_data, vars(level), as.factor) 

survey_data %>%
  filter(!participant == 95) %>% 
  mutate(level = fct_infreq(level)) %>% 
  ggplot(aes(level)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))

survey_data %>% 
  filter(is.na(level))

survey_data <- survey_data %>% 
  filter(!participant == 94)

View(survey_data)

survey_data %>% 
  count(level)

```

