---
title: "SEM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load libraries

```{r}
library(tidyverse)
library(readr)
library(lavaan)
library(mediation)
library(MASS)
library(psych)
library(Hmisc)
library(corrplot)
```
# Data prep

## define column type

```{r}
cleaned_df <- read_csv("survey_data_clean.csv")

# change to factor
cleaned_df <- cleaned_df %>% 
  mutate_at(vars(level, gender), as.factor) %>% 
  mutate(gender = gender == 'Female')

#change to numeric 
cleaned_df <- cleaned_df %>% 
  mutate_at(vars(work_experience, core_team_tenure, gender), as.numeric) 
psych::describe(cleaned_df$gender)
```
## check normality

```{r}
ggplot(aes(decision_quality), data=cleaned_df) +
  geom_density()
ggplot(aes(interdependence), data=cleaned_df) +
  geom_density()
ggplot(aes(team_structure), data=cleaned_df) +
  geom_density()
ggplot(aes(transactive_memory), data=cleaned_df) +
  geom_density()
ggplot(aes(knowledge_sharing), data=cleaned_df) +
  geom_density()

psych::describe(cleaned_df$core_team_tenure) 
psych::describe(cleaned_df$transactive_memory)
```

## prepare control variables

```{r}
cleaned_df <- cleaned_df %>% 
              mutate(career_level = fct_recode(level, "NA" = "Other (Please specify (optional)):"))

cleaned_df$core_team_tenure[is.na(cleaned_df$core_team_tenure)] <- mean(cleaned_df$core_team_tenure, na.rm=TRUE)
summary(cleaned_df$core_team_tenure)
```
## corraltion matrix

```{r}
small_df <- cleaned_df %>% 
  dplyr::select(decision_quality, team_structure, transactive_memory, knowledge_sharing, interdependence, team_members, core_team_tenure, work_experience, gender)

small_df
cor_mat <- cor(small_df, method = c("pearson", "kendall", "spearman"))
round(cor_mat, 2)

corrplot(cor_mat, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)

eigen(cor_mat)
max(eigen(cor_mat)$values)/min(eigen(cor_mat)$values)
kappa((cor_mat), exact = TRUE)

rcorr(as.matrix(small_df))
```
## center independent variables 

```{r}
cleaned_df$team_structure <- scale(cleaned_df$team_structure, center = TRUE, scale = FALSE)[,]
cleaned_df$interdependence <- scale(cleaned_df$interdependence, center = TRUE, scale = FALSE)[,]
cleaned_df$knowledge_sharing <- scale(cleaned_df$knowledge_sharing, center = TRUE, scale = FALSE)[,]
cleaned_df$transactive_memory <- scale(cleaned_df$transactive_memory, center = TRUE, scale = FALSE)[,]
cleaned_df$core_team_tenure <- scale(cleaned_df$core_team_tenure, center = TRUE, scale = FALSE)[,]
cleaned_df$work_experience <- scale(cleaned_df$work_experience, center = TRUE, scale = FALSE)[,]
cleaned_dfteam_members <- scale(cleaned_df$team_members, center = TRUE, scale = FALSE)[,]

# cleaned_df <- cleaned_df %>% mutate_at(vars(transactive_memory, team_structure, interdependence, knowledge_sharing, core_team_tenure, work_experience, team_members, intrinsic_motivation, group_identification), funs(scale(.)))
```
# Stepwise regression

```{r}
# STEP 1
decision_1 <- lm(decision_quality ~ gender + work_experience + team_members + core_team_tenure, data = cleaned_df)
summary(decision_1)

knowledge_1 <- lm(knowledge_sharing ~ gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(knowledge_1)

transactive_1 <- lm(transactive_memory ~ gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(transactive_1)

# STEP 2
decision_2 <- lm(decision_quality ~ team_structure + interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(decision_2)

knowledge_2 <- lm(knowledge_sharing ~ team_structure + interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(knowledge_2)

transactive_2 <- lm(transactive_memory ~ team_structure + interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(transactive_2)

# STEP 3
decision_3 <- lm(decision_quality ~ team_structure * interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(decision_3)

knowledge_3 <- lm(knowledge_sharing ~ team_structure * interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(knowledge_3)

transactive_3 <- lm(transactive_memory ~ team_structure * interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(transactive_3)

# Mediation Models

# Step 1

decision_3 <- lm(decision_quality ~ team_structure * interdependence + gender + team_members + work_experience + core_team_tenure, data = cleaned_df)
summary(decision_3)

decision_4 <- lm(decision_quality ~ gender + team_members + work_experience + core_team_tenure + team_structure * interdependence + transactive_memory, data = cleaned_df)
summary(decision_4)

decision_5 <- lm(decision_quality ~ gender + team_members + work_experience + core_team_tenure + team_structure * interdependence + transactive_memory + knowledge_sharing, data = cleaned_df)
summary(decision_5)

anova(decision_4, decision_5)
```
# Moderated Mediation

```{r}
library(mediation)
mediate <- mediation::mediate

Mod.Med.Model.1 <- lm(knowledge_sharing ~ team_structure * transactive_memory, data = cleaned_df); summary(Mod.Med.Model.1)

Mod.Med.Model.2 <- lm(decision_quality ~ team_structure * transactive_memory + knowledge_sharing, data = cleaned_df); summary(Mod.Med.Model.2)

low_trans_memory <- mean(cleaned_df$transactive_memory)-sd(cleaned_df$transactive_memory)
high_trans_memory <- mean(cleaned_df$transactive_memory)+sd(cleaned_df$transactive_memory)

mod_med_low_trans_memory <- mediate(Mod.Med.Model.1, Mod.Med.Model.2,
                             covariates = list(transactive_memory = low_trans_memory), 
                             boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 1000, treat = "team_structure", 
                             mediator = "knowledge_sharing")
summary(mod_med_low_trans_memory)

mod_med_high_trans_memory <- mediate(Mod.Med.Model.1, Mod.Med.Model.2,
                             covariates = list(transactive_memory = high_trans_memory), 
                             boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 1000, treat = "team_structure", 
                             mediator = "knowledge_sharing")
summary(mod_med_high_trans_memory)

mod_med_test_1 <- mediate(Mod.Med.Model.1, Mod.Med.Model.2,
                             boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 1000, treat = "team_structure", 
                             mediator = "knowledge_sharing")

test.modmed(mod_med_test_1, covariates.1 = list(transactive_memory = low_trans_memory), covariates.2 = list(transactive_memory = high_trans_memory), sims = 1000)

############# NO.2

Mod.Med.Model.3 <- lm(knowledge_sharing ~ team_structure * interdependence, data = cleaned_df); summary(Mod.Med.Model.3)

Mod.Med.Model.4 <- lm(decision_quality ~ team_structure + knowledge_sharing * interdependence, data = cleaned_df); summary(Mod.Med.Model.4)

low_inter <- mean(cleaned_df$interdependence)-sd(cleaned_df$interdependence)
high_inter <- mean(cleaned_df$interdependence)+sd(cleaned_df$interdependence)

mod_med_low_inter <- mediate(Mod.Med.Model.3, Mod.Med.Model.4,
                             covariates = list(interdependence = low_inter), boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 2000, treat = "team_structure", 
                             mediator = "knowledge_sharing")
summary(mod_med_low_inter)

mod_med_high_inter <- mediate(Mod.Med.Model.3, Mod.Med.Model.4,
                             covariates = list(interdependence = high_inter), boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 1000, treat = "team_structure", 
                             mediator = "knowledge_sharing")
summary(mod_med_high_inter)

mod_med_test_2 <- mediate(Mod.Med.Model.3, Mod.Med.Model.4,
                             boot = TRUE,
                             boot.ci.type = "bca",
                             sims = 1000, treat = "team_structure", 
                             mediator = "knowledge_sharing")

test.modmed(mod_med_test_2, covariates.1 = list(interdependence = low_inter), covariates.2 = list(interdependence = high_inter), sims = 1000)
```
# SEM models

## create interaction terms
```{r}
cleaned_df$inter_trans <- cleaned_df$transactive_memory*cleaned_df$interdependence
cleaned_df$inter_teamstr <- cleaned_df$interdependence*cleaned_df$team_structure
cleaned_df$inter_knowshare <-cleaned_df$interdependence*cleaned_df$knowledge_sharing
```
## run models

```{r}
model_final <- '
decision_quality ~ e1*knowledge_sharing + e2*interdependence + e3*inter_knowshare + f1*team_structure + f2*inter_teamstr + d1*transactive_memory + d2*inter_trans + team_members + core_team_tenure + work_experience + gender
knowledge_sharing ~ a*team_structure + b*transactive_memory

interdependence ~ interdependence.mean*1
interdependence ~~ interdependence.var*interdependence

direct1 := f1
direct2 := d1

indirect1:= a*e1
indirect2:= b*e1

total1 := direct1 + indirect1
total2 := direct2 + indirect2

prop_med1 := indirect1 / total1
prop_med2 := indirect2 / total2

ind_1_below:= a*(e1 + e3*(interdependence.mean-sqrt(interdependence.var)))
ind_1_above:= a*(e1 + e3*(interdependence.mean+sqrt(interdependence.var)))

ind_2_below:= b*(e1 + e3*(interdependence.mean-sqrt(interdependence.var)))
ind_2_above:= b*(e1 + e3*(interdependence.mean+sqrt(interdependence.var)))


direct_1_below := f1 + f2*(interdependence.mean-sqrt(interdependence.var))
direct_1_above := f1 + f2*(interdependence.mean+sqrt(interdependence.var))

direct_2_below := d1 + d2*(interdependence.mean-sqrt(interdependence.var))
direct_2_above := d1 + d2*(interdependence.mean+sqrt(interdependence.var))

cond_1_indirect := a*e3
cond_2_indirect := b*e3
cond_1_direct := f1*f2
cond_2_direct := d1*d2
'
model_fit_final <- sem(model_final, data = cleaned_df, se = "boot", bootstrap = 10000)
summary(model_fit_final, fit.measures = TRUE, standardized = TRUE, ci = T)


# this is when Transactive Memory is not supposed to have a direct effect on DQ:
model_lesscompli <- '
decision_quality ~ c1*knowledge_sharing + c2*interdependence + c3*inter_knowshare + a3*team_structure + a4*inter_teamstr + team_members + core_team_tenure
knowledge_sharing ~ a2*team_structure + b*transactive_memory
transactive_memory ~ a1*team_structure

direct1 := a3
direct2 := a2
indirect1:= a1*b
indirect2:= a2*c1
indirect3:= a1*b*c1
cond_indirect_1:= a2*c3
cond_indirect_2:= a1*b*c3
'
model_fit_lesscompli <- sem(model_lesscompli, data = cleaned_df, se = "boot", bootstrap = 10000)
summary(model_fit_lesscompli, fit.measures = TRUE, standardized = TRUE, ci = T)

modificationindices(model_fit_lesscompli, minimum.value = 20)
```
# Model comparisons

```{r}
model_with <- '
decision_quality ~ c1*knowledge_sharing + c2*interdependence + c3*inter_knowshare + d1*team_structure + d2*inter_teamstr + e1*transactive_memory + team_members + core_team_tenure + work_experience + gender
knowledge_sharing ~ a*team_structure + b*transactive_memory
'
model_fit_with <- sem(model_with, data = cleaned_df)
summary(model_fit_with, fit.measures = TRUE, standardized = TRUE, ci = T)

model_without <- '
decision_quality ~ c1*knowledge_sharing + c2*interdependence + c3*inter_knowshare + d1*team_structure + d2*inter_teamstr + team_members + core_team_tenure + work_experience + gender
knowledge_sharing ~ a*team_structure + b*transactive_memory
'
model_fit_without <- sem(model_without, data = cleaned_df)
summary(model_fit_without, fit.measures = TRUE, standardized = TRUE, ci = T)

anova(model_fit_with, model_fit_without)
summary(model_fit_with)
```
# Confirmatory Factor Analysis (CFA) for decision quality

```{r}
one_factor <- '
decision_quality =~ decision_compare_1 + 
                    decision_compare_2 + 
                    decision_compare_3 +
                    decision_general_1 + 
                    decision_general_2 + 
                    decision_general_3

decision_quality ~~ 1*decision_quality

# manifest variable covariances (uniquenesses)
  decision_compare_1 ~~ decision_compare_3
  decision_compare_3 ~~ decision_compare_2
  decision_compare_1 ~~ decision_compare_2
'

fit_one_fct <- cfa(one_factor, data = cleaned_df, std.lv=TRUE)
summary(fit_one_fct, fit.measures=TRUE, standardized=TRUE)

parameterEstimates(fit_one_fct, standardized=TRUE) 

modificationIndices(fit_one_fct, sort.=TRUE, minimum.value=3)

two_factor <- '
com_decision_quality =~ decision_compare_1 + 
                    decision_compare_2 + 
                    decision_compare_3
                    
gen_decision_quality =~ decision_general_1 + 
                    decision_general_2 + 
                    decision_general_3'

fit_two_fct <- cfa(two_factor, data = cleaned_df, std.lv=TRUE)
summary(fit_one_fct, fit.measures=TRUE, standardized=TRUE)

modificationIndices(fit_two_fct, sort.=TRUE, minimum.value=3)

anova(fit_one_fct, fit_two_fct)


levelled_factor <- '
com_decision_quality =~ decision_compare_1 + 
                    decision_compare_2 + 
                    decision_compare_3
                    
gen_decision_quality =~ decision_general_1 + 
                    decision_general_2 + 
                    decision_general_3

overall =~ com_decision_quality + gen_decision_quality'

levelled_fct <- cfa(levelled_factor, data = cleaned_df, std.lv=TRUE)
summary(fit_one_fct, fit.measures=TRUE, standardized=TRUE)
```
